import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";
import { PostHogProvider } from "../components/PostHogProvider";
import { ProfileContextProvider } from "@/contexts/profileContext";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "App | ConnectMe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PostHogProvider>
          <div className="app-scale-shell">
            {children}
          </div>
          {/* <SpeedInsights /> */}
        </PostHogProvider>
      </body>
    </html>
  );
}
