//Imports
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Inter constant
const inter = Inter({ subsets: ["latin"] });

// Metadata | Title ConnectMe
export const metadata: Metadata = {
  title: "App | ConnectMe",
  description: "Generated by create next app",
};

// RootLayout function
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
